quarkus.application.name=service-device-accesspoint
quarkus.http.port=8080
quarkus.http.cors.enabled=true
quarkus.http.cors.origins[0]=/.*/
quarkus.http.enable-compression=true

# Native: 包含静态资源
quarkus.native.resources.includes=META-INF/resources/**

# OpenAPI
quarkus.smallrye-openapi.path=/openapi